### ISSUE TITLE
Fix free card logic

### ISSUE THREAD

**Issue by CodeFatherG** [CodeFatherG/probi-oh#7]
# Expandable Free Card System Overhaul

- [x] New Free Card type
- [x] Expand gamestate to support openly processing and tracking cards
- [x] Write Free Card processor
- [x] Update simulation to branch free card optionsfor statistical analysis

**Comment by CodeFatherG** [comment]
Inspiration project [uses hard coded search strings ](https://github.com/flipflipshift/BasicYGOSim/blob/main/YugiohSim.py#L108) to perform free draws.

This approach has fallbacks and bugs in itself. Cards like Pot of Prosperity is [written to draw 6 cards](https://github.com/flipflipshift/BasicYGOSim/blob/main/YugiohSim.py#L126) however prosperity excavates 6, adds one to hand, then adds the rest to the bottom of the deck.

The aim is to create an expandable free card system that is not hardcoded in a way such that new cards can be supported (as long as their rules are already added) without maintenance. This should be done through the yaml system.

In simulation, instead of drawing free cards off the bat, the simulation should trigger free cards on a priority system incrementally based on if conditions succeed or not. This allows for bigger data on if you draw x free cards but only use y, what free cards you are wasting, and what free cards are used most.

Cost of free cards, such as banishing 10 from Pot of Desires should remain in the gamestate for future analysis. This allows for further statistics on how often you lose due to getting rid of cards

**Comment by CodeFatherG** [comment]
The following cards are identified and summarised

Pot of Desires - banish from deck and draw. OPT
Pot of Extravagance - banish from extra and draw. Must be first. No more draws
Pot of Prosperity - banish from extra and excavate and pick 1, return to bottom deck. OPT. No more draws
Upstart Goblin - -1000LP and draw
Allure of Darkness - draw and banish dark or discard hand
Into the Void - draw and discard at end
Pot of Duality - excavate 3, pick 1, shuffle rest. OPT. No SS
Trade-In - discard a lvl8 then draw 2
Spellbook of Knowledge (for Spellcaster decks) - discard spellcaster or spellbook and draw 2. OPT

By my evaluation these can be categorised by 4 main categories.
Cost: Cost must be paid to draw the cards.
OPT: once per turn.
Condition: There is a requirement after drawing (allure)
Restriction: The card imposes a restriction that affects the purposes of the simulation.

| Card                      | Cost  | OPT   | Condition | Restriction   |
| ---                       | ---   | ---   | ---       | ---           |
| Pot of Desires            | [ x ] | [ x ] |           |               |
| Pot of Extravagance       |       |       |           | [ x ]         |
| Pot of Prosperity         |       | [ x ] |           | [ x ]         |
| Upstart Goblin            | [ x ] |       |           |               |
| Allure of Darkness        |       |       | [ x ]     |               |
| Into the Void             |       |       |           |               |
| Pot of Duality            |       | [ x ] |           |               |
| Trade-In                  | [ x ] |       |           |               |
| Spellbook of Knowledge    | [ x ] | [ x ] |           |               |

Discard at end clauses are ignored as either you get your hand or you fail anyway. Likewise, for the purposes of this simulation SS clauses are not important. This information will be available in the report output but doesn't need to be considered for probability. Cost such as banishing from the extra also makes no difference to this sim and therefore is not included.

What I haven't covered here is excavate for cards like prosperity and duality and the pick mechanic. These aren't really categories but rather properties of the free part of the card. With this in mind I think that we can parameterize free cards as so.

```typescript
enum CostType {
    BanishFromDeck,
    BanishFromHand,
    PayLife,
    Discard,
}
```

```typescript
enum ConditionType {
    Discard,
    BanishFromHand,
    BanishFromDeck,
}
```

```typescript
enum RestrictionType {
    NoSpecialSummon,
    NoMoreDraws,
    NoPreviousDraws,
}
```

```typescript
interface FreeCardDetails {
    count: number;
    oncePerTurn: Boolean;
    cost?: {
        type: CostType;
        value: number | string[];
    };
    condition?: {
        type: ConditionType;
        value: number | string;
    };
    restriction?: RestrictionType[];
    excavate?: {
        count: number;
        pick: number;
    }
}
```

With this object we can declare these cards as so

```typescript
const potOfDesires: FreeCardDetails = {
    count: 2,
    oncePerTurn: true,
    cost: {
        type: CostType.BanishFromDeck,
        value: 10
    }
};

const potOfExtravagance: FreeCardDetails = {
    count: 2,
    oncePerTurn: false,
    restrictions: [RestrictionType.NoPreviousDraws, RestrictionType.NoMoreDraws]
};

const potOfProsperity: FreeCardDetails = {
    count: 1,
    oncePerTurn: true,
    restrictions: [RestrictionType.NoMoreDraws],
    excavate: {
        count: 6,
        pick: 1
    }
};

const upstartGoblin: FreeCardDetails = {
    count: 1,
    oncePerTurn: false,
    cost: {
        type: CostType.PayLife,
        value: -1000 // Negative to indicate opponent gains LP
    }
};

const allureOfDarkness: FreeCardDetails = {
    count: 2,
    oncePerTurn: false,
    condition: {
        type: ConditionType.BanishFromHand,
        value: "DARK"
    }
};

const intoTheVoid: FreeCardDetails = {
    count: 1,
    oncePerTurn: false
};

const potOfDuality: FreeCardDetails = {
    count: 1,
    oncePerTurn: true,
    excavate: {
        count: 3,
        pick: 1
    }
};

const tradeIn: FreeCardDetails = {
    count: 2,
    oncePerTurn: false,
    cost: {
        type: CostType.Discard,
        value: "Level 8"
    }
};

const spellbookOfKnowledge: FreeCardDetails = {
    count: 2,
    oncePerTurn: true,
    cost: {
        type: CostType.Discard,
        value: ["Spellcaster", "Spellbook"]
    }
};
```

This can therefore be detailed in the yaml input as so

```yaml
deck:
  Pot of Desires:
    qty: 3
    tags:
      - Draw
      - Banish
    free:
      count: 2
      oncePerTurn: true
      cost:
        type: BanishFromDeck
        value: 10

  Pot of Extravagance:
    qty: 3
    tags:
      - Draw
      - Banish
    free:
      count: 2
      oncePerTurn: false
      restrictions:
        - NoPreviousDraws
        - NoMoreDraws

conditions:
  - 1+ Pot of Desires
  - 1+ Pot of Extravagance
```

An extra step is required to convert string to enum values

```typescript
// Process the deck
for (const [cardName, cardDetails] of Object.entries(data.deck)) {
    if (cardDetails.free) {
        // Convert enum strings to actual enum values
        if (cardDetails.free.cost) {
            cardDetails.free.cost.type = CostType[cardDetails.free.cost.type as keyof typeof CostType];
        }
        if (cardDetails.free.condition) {
            cardDetails.free.condition.type = ConditionType[cardDetails.free.condition.type as keyof typeof ConditionType];
        }
        if (cardDetails.free.restrictions) {
            cardDetails.free.restrictions = cardDetails.free.restrictions.map(
                r => RestrictionType[r as keyof typeof RestrictionType]
            );
        }
    }
}
```

**Comment by CodeFatherG** [comment]
```typescript
enum CostType {
    BanishFromDeck = "BanishFromDeck",
    BanishFromHand = "BanishFromHand",
    PayLife = "PayLife",
    Discard = "Discard",
}

enum ConditionType {
    Discard = "Discard",
    BanishFromHand = "BanishFromHand",
    BanishFromDeck = "BanishFromDeck",
}

enum RestrictionType {
    NoSpecialSummon = "NoSpecialSummon",
    NoMoreDraws = "NoMoreDraws",
    NoPreviousDraws = "NoPreviousDraws",
}

interface FreeCardDetails {
    count: number;
    oncePerTurn: boolean;
    cost?: {
        type: CostType;
        value: number | string;
    };
    condition?: {
        type: ConditionType;
        value: number | string;
    };
    restrictions?: RestrictionType[];
    excavate?: {
        count: number;
        pick: number;
    }
}

interface CardDetails {
    qty: number;
    tags: string[];
    free?: FreeCardDetails;
}

interface DeckInput {
    deck: Record<string, CardDetails>;
    conditions: string[];
}
```

**Comment by CodeFatherG** [comment]
```yaml
deck:
  Pot of Desires:
    qty: 3
    tags:
      - Draw
      - Banish
    free:
      count: 2
      oncePerTurn: true
      cost:
        type: BanishFromDeck
        value: 10

  Pot of Extravagance:
    qty: 3
    tags:
      - Draw
      - Banish
    free:
      count: 2
      oncePerTurn: false
      restrictions:
        - NoPreviousDraws
        - NoMoreDraws

  Pot of Prosperity:
    qty: 3
    tags:
      - Draw
      - Banish
      - Excavate
    free:
      count: 1
      oncePerTurn: true
      restrictions:
        - NoMoreDraws
      excavate:
        count: 6
        pick: 1

  Upstart Goblin:
    qty: 3
    tags:
      - Draw
    free:
      count: 1
      oncePerTurn: false
      cost:
        type: PayLife
        value: -1000

  Allure of Darkness:
    qty: 3
    tags:
      - Draw
      - Banish
    free:
      count: 2
      oncePerTurn: false
      condition:
        type: BanishFromHand
        value: "DARK"

  Into the Void:
    qty: 3
    tags:
      - Draw
    free:
      count: 1
      oncePerTurn: false

  Card of Demise:
    qty: 3
    tags:
      - Draw
    free:
      count: 3
      oncePerTurn: true

  Pot of Duality:
    qty: 3
    tags:
      - Draw
      - Excavate
    free:
      count: 1
      oncePerTurn: true
      excavate:
        count: 3
        pick: 1

  Trade-In:
    qty: 3
    tags:
      - Draw
      - Discard
    free:
      count: 2
      oncePerTurn: false
      cost:
        type: Discard
        value: "Level 8"

  Spellbook of Knowledge:
    qty: 3
    tags:
      - Draw
      - Discard
    free:
      count: 2
      oncePerTurn: true
      cost:
        type: Discard
        value: "Spellcaster or Spellbook"

conditions:
  - 1+ Pot of Desires
  - 1+ Pot of Extravagance
  - 1+ Pot of Prosperity
  - 1+ Upstart Goblin
  - 1+ Allure of Darkness
  - 1+ Into the Void
  - 1+ Card of Demise
  - 1+ Pot of Duality
  - 1+ Trade-In
  - 1+ Spellbook of Knowledge
```
